// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC47NDSF7Y7ycykap5VtK1udyBOn_X0hfc',
    appId: '1:76932321091:web:a778eef78d6ca2834fa9f6',
    messagingSenderId: '76932321091',
    projectId: 'flutterfirstaider',
    authDomain: 'flutterfirstaider.firebaseapp.com',
    storageBucket: 'flutterfirstaider.appspot.com',
    measurementId: 'G-HWWPSG1CKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXdKWjyWrXSSwJrGU8kJGI9CL30dTDsq4',
    appId: '1:76932321091:android:6ca2dfdba4585fdd4fa9f6',
    messagingSenderId: '76932321091',
    projectId: 'flutterfirstaider',
    storageBucket: 'flutterfirstaider.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfOdMv3EF7_FJh-yMrQV4lMy2tflF24sw',
    appId: '1:76932321091:ios:e4ea4c7ede5b4aca4fa9f6',
    messagingSenderId: '76932321091',
    projectId: 'flutterfirstaider',
    storageBucket: 'flutterfirstaider.appspot.com',
    iosBundleId: 'com.example.firstAidProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfOdMv3EF7_FJh-yMrQV4lMy2tflF24sw',
    appId: '1:76932321091:ios:e4ea4c7ede5b4aca4fa9f6',
    messagingSenderId: '76932321091',
    projectId: 'flutterfirstaider',
    storageBucket: 'flutterfirstaider.appspot.com',
    iosBundleId: 'com.example.firstAidProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC47NDSF7Y7ycykap5VtK1udyBOn_X0hfc',
    appId: '1:76932321091:web:89385c0a15d595f84fa9f6',
    messagingSenderId: '76932321091',
    projectId: 'flutterfirstaider',
    authDomain: 'flutterfirstaider.firebaseapp.com',
    storageBucket: 'flutterfirstaider.appspot.com',
    measurementId: 'G-0T2B94RWD9',
  );
}
